export const MAIN_ROUTE = '/'
export const MENU_ROUTE = '/menu'
export const PROGRESS_ROUTE = '/progress'
export const INSIDES_ROUTE = '/insides'
export const WALLET_ROUTE = '/wallet'
export const MESSAGES_ROUTE = '/messages'
export const PROFILE_ROUTE = '/profile'
