import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import '../globals.css'

import { AOSInit } from '@/lib/aos'
import { cn } from '@/lib/utils'

const sora = Sora({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Digital Finance Dashboard',
    description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <AOSInit />
            <body className={cn('relative min-h-screen', sora.className)}>
                <div
                    className="absolute left-0 top-0 z-0 h-23vh w-full bg-mainPageBlackGradient"
                    data-aos="fade-in-zoom"
                />
                <main className="flex min-h-screen items-center justify-center">{children}</main>
            </body>
        </html>
    )
}
