import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import './globals.css'

import NavBar from '@/components/nav/NavBar'
import { cn } from '@/lib/utils'

const sora = Sora({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Digital Finance Dashboard',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={cn('relative min-h-screen', sora.className)}>
                <div className="absolute left-0 top-0 z-0 h-1/4 w-full bg-mainPageBlackGradient" />
                <NavBar />
                <main>{children}</main>
            </body>
        </html>
    )
}
